name: dart_restlib_common
description: A sample application
dev_dependencies:
  dart_restlib_testing:
    git: https://bordoley@code.google.com/p/dart-restlib.testing/
  unittest: any

#dependencies:
#  js: any
#  unittest: any